name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      TAG: "docker.pkg.github.com/${{github.repository}}/ubuntu-gfortran-fcm-make-netcdf:latest"

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${TAG}"
    - name: Test Docker image, basic
      run: |
        docker run --rm -v "${PWD}/test:/opt/test" "${TAG}" fcm make -C '/opt/test'
        docker run --rm -v "${PWD}/test:/opt/test" "${TAG}" '/opt/test/build/bin/hello.bin'
    - name: Test Docker image, build with netCDF
      run: |
        curl -L \
          'https://www.unidata.ucar.edu/software/netcdf/examples/programs/simple_xy_wr.f90' \
          -o 'test/src/simple_xy_wr.f90'
        docker run --rm -v "${PWD}/test:/opt/test" "${TAG}" \
          fcm make -C '/opt/test' -f '/opt/test/fcm-make-with-netcdf.cfg'
        docker run --rm -v "${PWD}/test:/opt/test" "${TAG}" \
          '/opt/test/build/bin/simple_xy_wr.bin'
    - name: Push Docker image to GPR
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        docker login -u "${GITHUB_REPOSITORY%%/*}" --password-stdin 'docker.pkg.github.com' <<<'${{secrets.GITHUB_TOKEN}}'
        docker push "${TAG}"
